name: Refresh Automatic Content

on:
  repository_dispatch:
    types: [gem-release]

  schedule:
    - cron: '0 6 * * *'
    - cron: '0 18 * * *'

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  refresh-automatic-content:
    runs-on: ubuntu-latest
    environment: automatic-content-refresh

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@472790540115ce5bd69d399a020189a8c87d641f # v1.247.0
      with:
        ruby-version: '3.4'

    - name: Fetch remote content
      run: |
        chmod +x bin/refresh_automatic_content
        ruby bin/refresh_remove_content

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        commit-message: 'chore: refresh automatic content'
        title: 'Automatic content updates'
        body: 'Automated update of automatic content'
        branch: automated/automatic-content-updates
        base: master
