name: Refresh Remote Content

on:
  # Run daily at 6 AM UTC
  schedule:
    - cron: '0 6 * * *'

  # Allow manual triggering for testing
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  refresh-remote-content:
    runs-on: ubuntu-latest
    environment: remote-content-refresh

    steps:
    - name: Checkout repository
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        token: ${{ secrets.REPO_TOKEN }}

    - name: Set up Ruby
      uses: ruby/setup-ruby@472790540115ce5bd69d399a020189a8c87d641f # v1.247.0
      with:
        ruby-version: '3.4'

    - name: Run changelog fetcher
      run: |
        chmod +x bin/refresh_remote_content
        ruby bin/refresh_remote_content

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: 'chore: refresh remote content'
        title: 'Remote content updates'
        body: 'Automated update of remote content'
        branch: automated/remote-content-updates
        base: master
