name: Sync GitHub Wiki

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: sync-github-wiki
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    environment: automatic-content-refresh
    steps:
      - name: Checkout docs repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          path: wiki

      - name: Checkout GitHub Wiki
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: karafka/karafka.wiki
          path: wiki/.gh
          token: ${{ secrets.REPO_TOKEN }}

      - name: Set up Ruby
        uses: ruby/setup-ruby@9eb537ca036ebaed86729dcb9309076e4c5c3b74 # v1.314.0
        with:
          ruby-version: '4.0.5'

      - name: Configure Git
        working-directory: wiki/.gh
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync content to GitHub Wiki
        working-directory: wiki
        run: bin/sync_gh
